// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.28;

library Errors {
    error AccountingToken();
    error ActiveUpdatePending();
    error AlreadyBaseToken();
    error AlreadyRootGuardian();
    error AmountOutTooLow();
    error BridgeAdapterAlreadyExists();
    error BridgeAdapterDoesNotExist();
    error BridgeStateMismatch();
    error CaliberAccountingStale(uint256 caliberChainId);
    error CaliberAlreadySet();
    error Create3ContractDeploymentFailed();
    error DirectManageFlashLoanCall();
    error EvmChainIdNotRegistered(uint256 chainId);
    error ExceededMaxDeposit();
    error ExceededMaxMint(uint256 shares, uint256 max);
    error ExceededMaxWithdraw(uint256 assets, uint256 max);
    error ForeignTokenNotRegistered(address _token, uint256 _foreignEvmChainId);
    error HubBridgeAdapterAlreadySet();
    error HubBridgeAdapterNotSet();
    error GroupIdNotProvided();
    error InstructionsMismatch();
    error InsufficientBalance();
    error InvalidAccounting();
    error InvalidAffectedToken();
    error InvalidChainId();
    error InvalidDebtFlag();
    error InvalidDecimals();
    error InvalidFeedRoute();
    error InvalidInputAmount();
    error InvalidInstructionProof();
    error InvalidInstructionType();
    error InvalidOutputToken();
    error InvalidPositionChangeDirection();
    error InvalidRecipientChainId();
    error InvalidTransferStatus();
    error LocalTokenNotRegistered(address _token, uint256 _foreignEvmChainId);
    error ManageFlashLoanReentrantCall();
    error MaxValueLossExceeded();
    error MessageAlreadyAuthorized();
    error Migrated();
    error MinOutputAmountExceedsInputAmount();
    error MismatchedLength();
    error MismatchedLengths();
    error MissingInstructionForGroup(uint256 groupId);
    error NegativeTokenPrice(address priceFeed);
    error NoPendingUpdate();
    error NonZeroBalance();
    error NotBaseToken();
    error NotCaliber();
    error NotCaliberMailbox();
    error NotController();
    error NotFactory();
    error NotFlashLoanModule();
    error NotMachine();
    error NotMachineEndpoint();
    error NotMigrated();
    error NotPendingMachine();
    error NotPreDepositVault();
    error NotRootGuardian();
    error OngoingCooldown();
    error OutTransferDisabled();
    error PendingBridgeTransfer();
    error PositionAccountingStale(uint256 posId);
    error PositionDoesNotExist();
    error PositionIsGrouped();
    error PriceFeedRouteNotRegistered(address token);
    error PriceFeedStale(address priceFeed, uint256 updatedAt);
    error ProtectedRootGuardian();
    error Create3ProxyDeploymentFailed();
    error RecoveryMode();
    error SameRoot();
    error SlippageProtection();
    error SpokeBridgeAdapterAlreadySet();
    error SpokeBridgeAdapterNotSet();
    error SpokeCaliberAlreadySet();
    error StaleData();
    error SwapFailed();
    error SwapperTargetsNotSet();
    error TargetAlreadyExists();
    error UnauthorizedCaller();
    error UnauthorizedSource();
    error UnexpectedMessage();
    error UnexpectedResultLength();
    error InvalidBridgeId();
    error WhChainIdNotRegistered(uint16 chainId);
    error ZeroBridgeAdapterAddress();
    error ZeroChainId();
    error ZeroGroupId();
    error ZeroPositionId();
    error ZeroSalt();
    error ZeroTokenAddress();
}
