[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]
evm_version = "cancun"
ast = true
build_info = true
extra_output = ["storageLayout"]
optimizer-runs = 200

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
sort_imports = true

[rpc_endpoints]
SEPOLIA = "${SEPOLIA_RPC_URL}"
ANVIL = "${ANVIL_RPC_URL}"
MAINNET = "${MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
