[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer-runs = 100_000
solc = "0.8.26"
evm_version = "cancun"


[fuzz]
runs = 256
max_test_rejects = 100000

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
sort_imports = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
